
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig, env } from "prisma/config";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.join(__dirname, "../.env") });

const rawDatabaseUrl = process.env.DATABASE_URL;
if (!rawDatabaseUrl || rawDatabaseUrl.includes("${")) {
  const dbUser = process.env.DB_USER ?? "";
  const dbPassword = process.env.DB_PASSWORD ?? "";
  const dbHost = process.env.DB_HOST ?? "localhost";
  const dbPort = process.env.DB_PORT ?? "5432";
  const dbName = process.env.DB_NAME ?? "";
  const dbSsl = process.env.DB_SSL ?? "false";
  const sslMode = dbSsl === "true" ? "require" : dbSsl === "false" ? "disable" : dbSsl;

  // dotenv does not expand ${VAR} placeholders by default.
  process.env.DATABASE_URL = `postgresql://${dbUser}:${dbPassword}@${dbHost}:${dbPort}/${dbName}?sslmode=${sslMode}`;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
